# Generated by Django 6.1.1 on 2026-09-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_subject_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="roll_no",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
