# Generated by Django 6.1.1 on 2026-09-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_attendancerecord_teacher_student_class_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
